-- Active: 1676911949936@@127.0.0.1@3306@movies
DROP TABLE IF EXISTS `movies`.`movie`;
CREATE TABLE IF NOT EXISTS `movies`.`movie`(
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `title` VARCHAR(50) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `release_date` DATE NOT NULL,
    `runtime` INT NOT NULL, 
    `rating` TEXT(5) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL
)